### ISSUE TITLE
Use buildkit-tekton (stable) into github actions workflow

### ISSUE THREAD

**Issue by vdemeester** [vdemeester/buildkit-tekton#56]
In order to dogfood, let's try to use mainly tekton pipeline in our CI
*but* on github workflow.

This most likely mean, define a "simple" (to begin with)
buildkit-tekton github action that is able to run it with `tkn-local`.

```yaml
- uses: vdemeester/tkn-local@v1
  with:
    dirs: .tekton
    run: .tekton/pullrequest.yaml
    pipelines-as-code: true
```

## Open questions
- Should there be an option for `tkn-pac` so that we do `tkn pac resolve … | tkn local run …` ?
  I think so 😇
